## Numpy- The fundamental package for scientific computing with Python

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types, with many operations being performed in compiled code for performance.


In [1]:
#importing the packages
import numpy as np
import math

Let's creating a simple 2D array, which; as you can see is simply a list of lists. You must be wondering then, why dont we simply keep it that way then; as a list of lists? Because a 2D 'array' and its additional supporting functions/attribute are much needed for data handling and do not come with simple lists.

In [2]:
#Creating a 2D array
b=np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

we can know the dimension of array with attribute shape

In [3]:
b.shape

(2, 3)

In [4]:
#accessing the elements from array
print(b)
b[0,0], b[0,1], b[1,0]

[[1 2 3]
 [4 5 6]]


(1, 2, 4)

Next we look at quick ways of creating some arrays with default values

In [5]:
#All zeros
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [6]:
#All ones
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [7]:
##All constants
np.full((3,2),math.pi)

array([[3.14159265, 3.14159265],
       [3.14159265, 3.14159265],
       [3.14159265, 3.14159265]])

In [9]:
#Identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
#Random vector
help(np.random.rand)

Help on built-in function rand:

rand(...) method of numpy.random.mtrand.RandomState instance
    rand(d0, d1, ..., dn)
    
    Random values in a given shape.
    
    .. note::
        This is a convenience function for users porting code from Matlab,
        and wraps `random_sample`. That function takes a
        tuple to specify the size of the output, which is consistent with
        other NumPy functions like `numpy.zeros` and `numpy.ones`.
    
    Create an array of the given shape and populate it with
    random samples from a uniform distribution
    over ``[0, 1)``.
    
    Parameters
    ----------
    d0, d1, ..., dn : int, optional
        The dimensions of the returned array, must be non-negative.
        If no argument is given a single Python float is returned.
    
    Returns
    -------
    out : ndarray, shape ``(d0, d1, ..., dn)``
        Random values.
    
    See Also
    --------
    random
    
    Examples
    --------
    >>> np.random.rand(3,2)
    arra

Learn more from documentation: https://numpy.org/devdocs/user/quickstart.html

In [16]:
#Random vector
#Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).
np.random.rand(5)

array([0.80765843, 0.67425004, 0.1843258 , 0.73121632, 0.67007076])

In [18]:
#Generates an array of shape, filled with random floats sampled from a univariate “normal” (Gaussian) distribution of mean 0 and variance 1
np.random.randn(3,2)

array([[-0.77461718, -0.70715012],
       [ 1.14973951, -1.55533349],
       [ 2.15318458,  0.84657131]])

In [19]:
#Returns array of numbers of specified size with given range of values
np.random.randint(high=10,low=1,size=(2,3))

array([[2, 9, 8],
       [7, 2, 1]])

In [21]:
#To create an array in sequence
x=np.arange(0,15)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [23]:
#To create a sequence with equally spaced elements
np.linspace(start=2,stop=10,num=15)

array([ 2.        ,  2.57142857,  3.14285714,  3.71428571,  4.28571429,
        4.85714286,  5.42857143,  6.        ,  6.57142857,  7.14285714,
        7.71428571,  8.28571429,  8.85714286,  9.42857143, 10.        ])

To create an array of required shape from the existing array- Use np.random.choice()
- The output will be different for each run, we can use replace= True in parameters to get fixed values

In [28]:
np.random.choice(x,6)

array([ 7,  9, 13,  9,  4, 12])

In [29]:
np.random.choice(x,6,replace=False)

array([ 2,  0, 14, 11,  4,  8])

In [30]:
np.random.choice(['a','b','c'],9)

array(['c', 'c', 'b', 'a', 'c', 'b', 'b', 'b', 'a'], dtype='<U1')

In [31]:
np.random.choice(['a','b','c'],1000,p=[.3,.3,.4])

array(['b', 'c', 'c', 'c', 'a', 'a', 'b', 'c', 'c', 'c', 'a', 'b', 'a',
       'a', 'a', 'b', 'c', 'b', 'c', 'b', 'b', 'c', 'b', 'c', 'b', 'a',
       'c', 'c', 'b', 'a', 'b', 'c', 'c', 'b', 'b', 'c', 'c', 'a', 'b',
       'c', 'b', 'b', 'a', 'c', 'c', 'a', 'a', 'a', 'a', 'b', 'a', 'b',
       'a', 'b', 'c', 'b', 'b', 'c', 'c', 'c', 'c', 'a', 'c', 'a', 'c',
       'c', 'c', 'a', 'a', 'c', 'a', 'a', 'c', 'c', 'b', 'a', 'a', 'b',
       'c', 'a', 'c', 'a', 'c', 'c', 'c', 'b', 'a', 'b', 'b', 'c', 'c',
       'c', 'b', 'a', 'a', 'c', 'a', 'b', 'b', 'b', 'c', 'b', 'c', 'a',
       'a', 'b', 'b', 'c', 'c', 'b', 'c', 'b', 'c', 'a', 'a', 'c', 'c',
       'c', 'a', 'b', 'b', 'b', 'c', 'c', 'c', 'c', 'b', 'c', 'b', 'b',
       'c', 'a', 'c', 'a', 'b', 'c', 'a', 'b', 'c', 'b', 'c', 'b', 'a',
       'a', 'a', 'b', 'a', 'c', 'c', 'b', 'b', 'c', 'a', 'a', 'b', 'a',
       'c', 'c', 'c', 'b', 'c', 'b', 'b', 'c', 'c', 'a', 'a', 'b', 'a',
       'c', 'b', 'a', 'c', 'c', 'a', 'b', 'a', 'b', 'c', 'b', 'b